base_url: "https://pt.sjtu.edu.cn"
torrents_dir: "unsync/torrents"
user_info_file: "unsync/parms.pickle"
patterns_file: "example/patterns.txt"
db_file: "unsync/grapes.db"
torrent_schema:
  - name: "torrent_id"
    dbtype: "INTEGER PRIMARY KEY"
  - name: "torrent_ptid"
    dbtype: "TEXT"
  - name: "torrent_title"
    dbtype: "TEXT"
  - name: "torrent_file"
    dbtype: "TEXT"
  - name: "t_add"
    dbtype: "TIMESTAMP"
  - name: "pattern_id"
    dbtype: "INTEGER"
  - name: "t_start"
    dbtype: "TIMESTAMP"
  - name: "t_complete"
    dbtype: "TIMESTAMP"
  - name: "t_remove"
    dbtype: "TIMESTAMP"
pattern_schema:
  - name: "pattern_id"
    dbtype: "INTEGER PRIMARY KEY"
  - name: "value"
    dbtype: "TEXT"
  - name: "t_add"
    dbtype: "TIMESTAMP"
  - name: "t_remove"
    dbtype: "TIMESTAMP"
